<?php

/**
 * @file
 * Install file for cms_content_sync_views.
 */

/**
 * Implements hook_install().
 */
function cms_content_sync_views_install() {
  // Set module weight higher then the cms_content_sync module to ensure
  // update hooks are triggered after it.
  module_set_weight('cms_content_sync_views', 1);

  // Cache rebuild is require, otherwise the module weight does not take effect.
  drupal_flush_all_caches();
}
